package com.richardspace.carrental;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Incident implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "VehicleID")
	private java.lang.String vehicle;

	@org.kie.api.definition.type.Label(value = "Description")
	private java.lang.String description;

	@org.kie.api.definition.type.Label(value = "State")
	private java.lang.String state;

	@org.kie.api.definition.type.Label(value = "ID")
	private java.lang.String id;

	public Incident() {
	}

	public java.lang.String getVehicle() {
		return this.vehicle;
	}

	public void setVehicle(java.lang.String vehicle) {
		this.vehicle = vehicle;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public java.lang.String getState() {
		return this.state;
	}

	public void setState(java.lang.String state) {
		this.state = state;
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public Incident(java.lang.String vehicle, java.lang.String description,
			java.lang.String state, java.lang.String id) {
		this.vehicle = vehicle;
		this.description = description;
		this.state = state;
		this.id = id;
	}

}