package com.richardspace.carrental;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Vehicles implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Vehicles() {
    }




}