package com.richardspace.carrental;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.xml.bind.annotation.XmlRootElement
public class Vehicle implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Id")
	private java.lang.String id;
	@org.kie.api.definition.type.Label("Model")
	private java.lang.String model;
	@org.kie.api.definition.type.Label("State")
	private java.lang.String state;
	@org.kie.api.definition.type.Label("Vin")
	private java.lang.String vin;

	@org.kie.api.definition.type.Label(value = "Location")
	private java.lang.String location;

	public Vehicle() {
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.String getModel() {
		return this.model;
	}

	public void setModel(java.lang.String model) {
		this.model = model;
	}

	public java.lang.String getState() {
		return this.state;
	}

	public void setState(java.lang.String state) {
		this.state = state;
	}

	public java.lang.String getVin() {
		return this.vin;
	}

	public void setVin(java.lang.String vin) {
		this.vin = vin;
	}

	public java.lang.String getLocation() {
		return this.location;
	}

	public void setLocation(java.lang.String location) {
		this.location = location;
	}

	public Vehicle(java.lang.String id, java.lang.String model,
			java.lang.String state, java.lang.String vin,
			java.lang.String location) {
		this.id = id;
		this.model = model;
		this.state = state;
		this.vin = vin;
		this.location = location;
	}

}